### ISSUE TITLE
Wrong values determined and transmitted

### ISSUE THREAD

**Issue by daniel-streetec** [christophmoar/abrpTelemetrySmartInjector#1]
Hi,
I've setup the adapter and iobroker on my Pi4. Its running good but the values transmitted to ABRP are wrong.

e.g. SOC is 59:
http://192.168.1.31:8087/getBulk/smart-eq.0.**VIN**.status.additionalVehicleStatus.electricVehicleStatus.chargeLevel
returns
[{"id":"smart-eq.0.**VIN**.status.additionalVehicleStatus.electricVehicleStatus.chargeLevel","val":"59","ts":1709279704082,"ack":true}]

but abrp transmits "NULL"
(3/1/2024, 8:10:04 AM) INFO: Sending telemetry to ABRP {"utc":1709280604,"soc":null,"is_charging":false,"is_parked":false,"ext_temp":null,"est_battery_range":0}

http://192.168.1.31:8087/getBulk/smart-eq.0.**VIN**.status.additionalVehicleStatus.electricVehicleStatus.distanceToEmptyOnBatteryOnly
returns 
[{"id":"smart-eq.0.**VIN**.status.additionalVehicleStatus.electricVehicleStatus.distanceToEmptyOnBatteryOnly","val":"116","ts":1709280603526,"ack":true}]

ENV file looks like follows:
ABRP_TOKEN=**TOKEN**
PREFIX_IOBROKER_STATE=smart-eq.0.**VIN**
PREFIX_IOBROKER_URL=http://192.168.1.31:8087/getBulk/

Can you advise?

**Comment by daniel-streetec** [comment]
Found the issue, it was a missing "." after the VIN in the config. Would be a simple check to add it if it's missing.

**Comment by christophmoar** [comment]
Hi Daniel, thanks for finding out/closing, you are right , would be an easy check, let's say the whole thing has been put together without much sanity checks.

I know the trailing dot is an issue, I wrote in the documentation

`"where HES**************. is your VIN followed by a single closing period."`

but I guess it needs to be much clearer, you are right :)
